### ISSUE TITLE
Unnecessary </div> tag

### ISSUE THREAD

**Issue by gdedi001** [thill1982/f1-3-c2p1-colmar-academy#2]
When I opened your project in my editor I noticed that you had an extra closing tag. Make sure to remove it.
https://github.com/thill1982/f1-3-c2p1-colmar-academy/blob/master/Capstone-Colmar/index.html#L33

**Comment by thill1982** [comment]
Thanks, this has now been removed. Is there an easy way to validate this within Atom (Windows)? I couldn't find a way to validate all HTML tags in it.

**Comment by gdedi001** [comment]
not sure, I don't use atom
