### ISSUE TITLE
Use id

### ISSUE THREAD

**Issue by gdedi001** [thill1982/f1-3-c2p1-colmar-academy#3]
This is an example of when you should use `id` attributes instead. Since this only appears once in your code class should not be used.
https://github.com/thill1982/f1-3-c2p1-colmar-academy/blob/master/Capstone-Colmar/index.html#L85

**Comment by thill1982** [comment]
Thanks for your feedback. I do recall the learning material referencing the use of IDs when only used once in the code. My thinking behind this was potential future proofing if the code was to change and that class was to be used elsewhere, and with IDs having the highest priority it could lead to override issues. With a class in place I could override it with an ID in future if needed. I guess I'm thinking too much into it so will use IDs in future when the code is only used once.
