### ISSUE TITLE
Great job using semantic tags

### ISSUE THREAD

**Issue by gdedi001** [thill1982/f1-3-c2p1-colmar-academy#4]
Great job using these, the whole point of HTML5 is to make your code semantic aka meaningful!
https://github.com/thill1982/f1-3-c2p1-colmar-academy/blob/master/Capstone-Colmar/index.html#L18-L31
https://github.com/thill1982/f1-3-c2p1-colmar-academy/blob/master/Capstone-Colmar/index.html#L181-L187

**Comment by thill1982** [comment]
Thanks for your comments. I'll continue to use them even more so to ensure my sites better support ARIA too.
